\set ON_ERROR_STOP on

CREATE ROLE dpg_staging_migrator
  LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS
  PASSWORD :'migrator_password';
CREATE ROLE dpg_staging_app
  LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS
  PASSWORD :'app_password';

ALTER DATABASE dpg_isolated_staging OWNER TO dpg_staging_migrator;
COMMENT ON DATABASE dpg_isolated_staging IS 'dongphugia:isolated-staging:v1';

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS plpgsql;
