import fs from 'node:fs/promises'
import path from 'node:path'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const phaseD = require('../../src/lib/content-review/phase-d-checkpoint.ts') as typeof import('../../src/lib/content-review/phase-d-checkpoint')
const { POLICY_HASH } = require('../../src/lib/content-review/policy-contract.ts') as typeof import('../../src/lib/content-review/policy-contract')

const root = process.cwd()
const packagePath = path.join(root, 'scripts/content-review/private/leo-493-phase-d-checkpoint-package.json')
const publicPath = path.join(root, 'docs/review-bundles/leo-493-phase-d-checkpoint-dashboard.html')
const privatePath = path.join(root, 'scripts/content-review/private/leo-493-phase-d-checkpoint-dashboard.html')

function stable(value: unknown): unknown {
    if (Array.isArray(value)) return value.map(stable)
    if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([left], [right]) => left.localeCompare(right)).map(([key, nested]) => [key, stable(nested)]))
    return value
}

function html(model: unknown): string {
    const payload = JSON.stringify(model).replace(/</g, '\\u003c')
    return `<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LEO-493 Phase D checkpoint</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#172033;background:#f5f7fb}body{margin:0}.wrap{max-width:1440px;margin:auto;padding:24px}.top{display:flex;gap:12px;align-items:end;justify-content:space-between;flex-wrap:wrap}.muted{color:#5c6678;font-size:13px}.counts{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px;margin:18px 0}.count{background:white;border:1px solid #dce2ec;border-radius:12px;padding:14px}.count strong{display:block;font-size:28px;margin-top:6px}.bar{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.bar>*{padding:9px 10px;border:1px solid #cbd4e1;background:white;border-radius:8px}.tabs button,.decision button{cursor:pointer}.tabs{display:flex;gap:8px;margin:16px 0}.tabs button.active{background:#1f4d89;color:white}.panel{background:white;border:1px solid #dce2ec;border-radius:12px;padding:16px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:16px}.card{background:white;border:1px solid #dce2ec;border-radius:12px;overflow:hidden}.cardhead{padding:14px;border-bottom:1px solid #edf0f5;display:flex;justify-content:space-between;gap:10px}.badge{display:inline-block;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:700;background:#e8eef8}.KEEP_PRODUCT{background:#d9f3e4}.KEEP_TEMPORARY{background:#fff0c7}.KEEP_TECHNICAL{background:#dcecff}.HUMAN_REVIEW,.REMOVE_HITA_SHOWROOM{background:#ffd9d9}.media{min-height:220px;background:#eef2f7;display:flex;align-items:center;justify-content:center}.media img{display:block;width:100%;max-height:360px;object-fit:contain}.media .manual{padding:30px;text-align:center}.body{padding:14px}.body h3{margin:0 0 8px}.decision{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.decision button{font-size:12px;border:1px solid #bfc9d8;background:#fff;border-radius:6px;padding:6px}.decision button.selected{outline:2px solid #1f4d89}.tech{margin-top:10px}.diff{background:#fff8db;border-left:3px solid #d39e00;padding:10px;white-space:pre-wrap}.content{display:grid;grid-template-columns:1fr 1fr;gap:12px}.content section{border:1px solid #e1e6ef;border-radius:8px;padding:12px;overflow:auto}.content img{max-width:100%;height:auto}.empty{padding:30px;color:#5c6678;text-align:center}@media(max-width:720px){.counts{grid-template-columns:repeat(2,1fr)}.cards{grid-template-columns:1fr}.content{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><div class="top"><div><h1>LEO-493 · Phase D checkpoint</h1><div class="muted">30 sản phẩm · dashboard offline · binding kiểm tra trước khi xem</div></div><button id="export">Xuất quyết định JSON</button></div><div id="binding" class="panel"></div><div class="counts" id="counts"></div><div class="tabs"><button id="mediaTab" class="active">Media Review</button><button id="contentTab">Content Review</button></div><div id="mediaView"><div class="bar"><input id="search" placeholder="Tìm SKU / tên sản phẩm"><select id="action"><option value="">Mọi quyết định</option><option>KEEP_PRODUCT</option><option>KEEP_TECHNICAL</option><option>KEEP_TEMPORARY</option><option>HUMAN_REVIEW</option><option>REMOVE_HITA_SHOWROOM</option></select><select id="family"><option value="">Mọi nhóm</option></select><select id="confidence"><option value="">Mọi độ tin cậy</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></div><div id="cards" class="cards"></div></div><div id="contentView" hidden><div class="bar"><input id="contentSearch" placeholder="Tìm SKU / tên sản phẩm"><select id="contentStatus"><option value="">Mọi trạng thái</option><option>FIRST_PASS_PASS</option><option>HUMAN_REVIEW</option></select></div><div id="contentCards" class="cards"></div></div></main><script>const MODEL=${payload};
const state={images:{},products:{}};const labels={KEEP_PRODUCT:'GIỮ — Hình sản phẩm',KEEP_TECHNICAL:'GIỮ — Bản vẽ/HDSD',KEEP_TEMPORARY:'GIỮ TẠM — Chưa chứng minh nguồn, không phải showroom Hita',HUMAN_REVIEW:'CẦN XEM',REMOVE_HITA_SHOWROOM:'XOÁ — Showroom/cửa hàng Hita'};const allMedia=()=>MODEL.products.flatMap(p=>p.media.map(m=>({...m,product:p})));const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const saved=localStorage.getItem('leo493-phase-d-decisions');if(saved)try{const x=JSON.parse(saved);Object.assign(state.images,x.images||{});Object.assign(state.products,x.products||{})}catch{}
function save(){localStorage.setItem('leo493-phase-d-decisions',JSON.stringify(stable(state)))}function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,n])=>[k,stable(n)]));return v}
function countView(){const media=allMedia();const keep=media.filter(m=>!['REMOVE_HITA_SHOWROOM','HUMAN_REVIEW'].includes(m.action)).length;const remove=media.filter(m=>m.action==='REMOVE_HITA_SHOWROOM').length;const review=media.filter(m=>m.action==='HUMAN_REVIEW').length;document.querySelector('#counts').innerHTML=[['Tổng ảnh',media.length],['Giữ',keep],['Xoá Hita',remove],['Cần xem',review]].map(x=>'<div class="count"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('')}
function preview(m){if(!MODEL.privateMedia)return '<div class="manual">Ảnh đã được ẩn trong public artifact.<br><span class="muted">Fingerprint: '+esc(m.fingerprint)+'</span></div>';if(m.host==='Bunny CDN'&&m.url)return '<img loading="lazy" src="'+esc(m.url)+'" alt="'+esc(m.product.name)+'">';if(m.host==='Hita'&&m.url)return '<div class="manual">Hita manual-only — không tự tải<br><button class="manualHita" data-url="'+esc(m.url)+'">Mở từng ảnh thủ công</button></div>';return '<div class="manual">CẦN XEM · không có preview tự động</div>'}
function renderMedia(){const term=document.querySelector('#search').value.toLocaleLowerCase();const action=document.querySelector('#action').value;const family=document.querySelector('#family').value;const confidence=document.querySelector('#confidence').value;const items=allMedia().filter(m=>(!term||((m.product.sku+' '+m.product.name).toLocaleLowerCase().includes(term)))&&(!action||m.action===action)&&(!family||m.product.family===family)&&(!confidence||m.classification.confidence===confidence));document.querySelector('#cards').innerHTML=items.length?items.map(m=>{const key=m.product.id+':'+m.sourceId;const decision=state.images[key]||m.action;return '<article class="card"><div class="media">'+preview(m)+'</div><div class="cardhead"><div><h3>'+esc(m.product.sku)+'</h3><div class="muted">'+esc(m.product.name)+' · '+esc(m.kind)+' · '+esc(m.product.family)+'</div></div><span class="badge '+decision+'">'+esc(labels[decision]||decision)+'</span></div><div class="body"><div class="decision">'+Object.keys(labels).map(a=>'<button class="'+(decision===a?'selected':'')+'" onclick="chooseImage('+JSON.stringify(key)+','+JSON.stringify(a)+')">'+esc(labels[a])+'</button>').join('')+'</div><details class="tech"><summary>Chi tiết kỹ thuật</summary><p class="muted">action đề xuất: '+esc(m.action)+' · confidence: '+esc(m.classification.confidence)+' · origin: '+esc(m.classification.origin)+' · placement: '+esc(m.placement)+' · duplicate: '+esc(m.duplicateOf||'không')+'</p><p>'+esc(m.classification.evidence)+'</p><p class="muted">visual cluster: '+esc(m.classification.visualCluster)+' · fingerprint: '+esc(m.fingerprint)+'</p></details></div></article>'}).join(''):'<div class="panel empty">Không có media phù hợp bộ lọc.</div>';countView()}
function chooseImage(key,value){state.images[key]=value;save();renderMedia()}function renderContent(){const term=document.querySelector('#contentSearch').value.toLocaleLowerCase();const status=document.querySelector('#contentStatus').value;const items=MODEL.products.filter(p=>(!term||((p.sku+' '+p.name).toLocaleLowerCase().includes(term)))&&(!status||p.editorialStatus===status));document.querySelector('#contentCards').innerHTML=items.map(p=>'<article class="card"><div class="cardhead"><div><h3>'+esc(p.sku)+'</h3><div class="muted">'+esc(p.name)+' · '+esc(p.family)+'</div></div><span class="badge">'+esc(p.editorialStatus)+'</span></div><div class="body"><p>Before/After ratio: '+Number(p.editorial.ratio).toFixed(3)+' · ảnh embedded: '+p.media.filter(m=>m.kind===\'embedded\').length+' · placement: '+p.media.filter(m=>m.kind===\'embedded\').map(m=>m.sourceId).join(', ')||'không có'+'</p><div class="decision"><button class="chooseProduct" data-id="'+esc(String(p.id))+'" data-value="APPROVE">Duyệt cục bộ</button><button class="chooseProduct" data-id="'+esc(String(p.id))+'" data-value="REVIEW">Cần xem</button></div><details open><summary>Before / After / Diff / Preview</summary><div class="content"><section><h4>Before</h4>'+p.beforeHtml+'</section><section><h4>After · inline placement</h4>'+p.afterHtml+'</section></div><details><summary>Diff</summary><div class="diff">'+esc(JSON.stringify(p.diff))+'</div></details><details><summary>Sanitized Preview</summary>'+p.previewHtml+'</details></details></div></article>').join('')}
function chooseProduct(key,value){state.products[key]=value;save();renderContent()}document.addEventListener('click',event=>{const button=event.target.closest('.manualHita');if(button)window.open(button.dataset.url,'_blank','noopener');const productButton=event.target.closest('.chooseProduct');if(productButton)chooseProduct(productButton.dataset.id,productButton.dataset.value)});document.querySelector('#binding').innerHTML='<strong>Binding: '+esc(MODEL.bindingStatus)+'</strong> · policy '+esc(MODEL.policyHash)+' · snapshot '+esc(MODEL.snapshotHash)+' · proposal '+esc(MODEL.proposalHash)+' · commit '+esc(MODEL.sourceCommit);const families=[...new Set(MODEL.products.map(p=>p.family))].sort();document.querySelector('#family').innerHTML+='<option>'+families.join('</option><option>')+'</option>';document.querySelector('#mediaTab').onclick=()=>{mediaView.hidden=false;contentView.hidden=true;mediaTab.classList.add('active');contentTab.classList.remove('active')};document.querySelector('#contentTab').onclick=()=>{mediaView.hidden=true;contentView.hidden=false;contentTab.classList.add('active');mediaTab.classList.remove('active');renderContent()};['search','action','family','confidence'].forEach(id=>document.querySelector('#'+id).oninput=renderMedia);['contentSearch','contentStatus'].forEach(id=>document.querySelector('#'+id).oninput=renderContent);document.querySelector('#export').onclick=()=>{const payload=stable({schemaVersion:MODEL.schemaVersion,dashboard:MODEL.dashboard,packageHash:MODEL.packageHash,proposalHash:MODEL.proposalHash,policyHash:MODEL.policyHash,snapshotHash:MODEL.snapshotHash,cohortHash:MODEL.cohortHash,checkpointHash:MODEL.checkpointHash,sourceHash:MODEL.sourceHash,sourceCommit:MODEL.sourceCommit,products:state.products,images:state.images});const blob=new Blob([JSON.stringify(payload,null,2)+'\\n'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='leo-493-phase-d-decisions.json';a.click();URL.revokeObjectURL(a.href)};renderMedia();</script></body></html>\n`
}

async function main() {
    const value = JSON.parse(await fs.readFile(packagePath, 'utf8')) as phaseD.PhaseDCheckpointPackage
    phaseD.assertPhaseDCheckpointBinding(value, POLICY_HASH, value.snapshotHash, value.sourceCommit)
    const publicModel = phaseD.buildPhaseDDashboardModel(value, 'public')
    const privateModel = phaseD.buildPhaseDDashboardModel(value, 'private')
    await fs.writeFile(publicPath, html(publicModel), 'utf8')
    await fs.writeFile(privatePath, html(privateModel), 'utf8')
    console.log(`PHASE_D_DASHBOARD_PASS public=${publicPath} private=${privatePath} products=${value.records.length}`)
}

main().catch((error) => { console.error(error instanceof Error ? error.message : 'Phase D dashboard build failed'); process.exitCode = 1 })
