import fs from 'node:fs/promises'
import path from 'node:path'
import { createRequire } from 'node:module'
import type { Prisma } from '@prisma/client'
import type { ProductContentInput } from '../../src/lib/content-review/types'

const require = createRequire(import.meta.url)
const { generateContentReviewProposal } = require('../../src/lib/content-review/proposal.ts') as typeof import('../../src/lib/content-review/proposal')
const { hashObject } = require('../../src/lib/content-review/hash.ts') as typeof import('../../src/lib/content-review/hash')
const { CONTENT_REVIEW_SOURCE } = require('../../src/lib/content-review/types.ts') as typeof import('../../src/lib/content-review/types')

function argumentValue(name: string): string | undefined {
    const prefix = `${name}=`
    return process.argv.find(value => value.startsWith(prefix))?.slice(prefix.length)
}

function validateInputs(value: unknown): ProductContentInput[] {
    if (!Array.isArray(value) || value.length === 0) throw new Error('Input must contain products')
    return value.map((item, index) => {
        if (!item || typeof item !== 'object') throw new Error(`Invalid product at index ${index}`)
        const product = item as ProductContentInput
        if (!Number.isInteger(product.id) || !product.sku || !product.name || !product.sourceUrl) {
            throw new Error(`Missing product identity at index ${index}`)
        }
        return { ...product, descriptionHtml: product.descriptionHtml || '' }
    })
}

async function main() {
    const fixturePath = argumentValue('--input') || path.join(
        process.cwd(),
        'scripts/content-review/fixtures/pilot-products.json',
    )
    const inputs = validateInputs(JSON.parse(await fs.readFile(fixturePath, 'utf8')))
    const proposals = await Promise.all(inputs.map(input => generateContentReviewProposal(input)))
    const summary = {
        source: CONTENT_REVIEW_SOURCE,
        mode: process.argv.includes('--write') ? 'review-tables-write' : 'dry-run',
        products: proposals.length,
        proposals_hash: hashObject(proposals.map(item => item.proposalHash)),
        pending_images: proposals.reduce(
            (total, item) => total + item.after.images.filter(image => image.decision === 'HUMAN_REVIEW').length,
            0,
        ),
        existing_bunny_keep: proposals.reduce(
            (total, item) => total + item.after.images.filter(image => image.decision === 'KEEP').length,
            0,
        ),
    }

    if (!process.argv.includes('--write')) {
        console.log(JSON.stringify(summary, null, 2))
        return
    }
    if (process.env.NODE_ENV === 'production') throw new Error('Production writes are forbidden')
    if (process.env.CONTENT_REVIEW_ALLOW_WRITE !== 'review-tables-only') {
        throw new Error('Set CONTENT_REVIEW_ALLOW_WRITE=review-tables-only for explicit non-production review-table writes')
    }

    const { default: prisma } = await import('../../src/lib/prisma')
    const requestedRunId = Number(argumentValue('--run-id'))
    const run = Number.isInteger(requestedRunId) && requestedRunId > 0
        ? await prisma.crawl_runs.findFirstOrThrow({ where: { id: requestedRunId, source: CONTENT_REVIEW_SOURCE } })
        : await prisma.crawl_runs.create({
            data: {
                source: CONTENT_REVIEW_SOURCE,
                brand_slug: 'fixture-pilot',
                status: 'running',
                input: { input_hash: hashObject(inputs), fixture: path.basename(fixturePath) },
            },
        })

    for (const [index, proposal] of proposals.entries()) {
        const input = inputs[index]
        const snapshot = await prisma.crawl_product_snapshots.upsert({
            where: {
                source_source_url_crawl_run_id: {
                    source: CONTENT_REVIEW_SOURCE,
                    source_url: input.sourceUrl,
                    crawl_run_id: run.id,
                },
            },
            create: {
                crawl_run_id: run.id,
                source: CONTENT_REVIEW_SOURCE,
                source_url: input.sourceUrl,
                source_product_id: String(input.id),
                sku: input.sku,
                raw_payload: input as unknown as Prisma.InputJsonValue,
                normalized_payload: proposal as unknown as Prisma.InputJsonValue,
                content_hash: proposal.baseHash,
                status: 'proposal',
            },
            update: {
                normalized_payload: proposal as unknown as Prisma.InputJsonValue,
                content_hash: proposal.baseHash,
                status: 'proposal',
            },
        })
        const decision = await prisma.crawl_import_decisions.upsert({
            where: { crawl_snapshot_id: snapshot.id },
            create: {
                crawl_snapshot_id: snapshot.id,
                target_product_id: input.id,
                decision: 'draft',
                reason: 'Generated by source-only content review pipeline',
                import_payload: proposal as unknown as Prisma.InputJsonValue,
            },
            update: {
                decision: 'draft',
                reason: 'Regenerated idempotently; approval invalidated',
                reviewer_id: null,
                reviewed_at: null,
                import_payload: proposal as unknown as Prisma.InputJsonValue,
                updated_at: new Date(),
            },
        })
        await prisma.audit_logs.create({
            data: {
                user_id: run.created_by,
                action: 'CONTENT_REVIEW_PROPOSAL_GENERATED',
                entity_type: 'crawl_import_decisions',
                entity_id: decision.id,
                new_value: {
                    source: CONTENT_REVIEW_SOURCE,
                    reason: 'Source-only proposal generation',
                    proposal_version: proposal.version,
                    proposal_hash: proposal.proposalHash,
                    base_hash: proposal.baseHash,
                },
            },
        })
    }
    await prisma.crawl_runs.update({
        where: { id: run.id },
        data: { status: 'completed', finished_at: new Date(), summary },
    })
    console.log(JSON.stringify({ ...summary, crawl_run_id: run.id }, null, 2))
    await prisma.$disconnect()
}

main().catch(error => {
    console.error(error instanceof Error ? error.message : error)
    process.exitCode = 1
})
