-- MS885 normalized Product Family and configuration-group migration.
-- PostgreSQL origin only; never execute through prisma/migrations.
--
-- This migration deliberately does not read or write products.variant_group or
-- products.variant_group_id. Product/PDP identity and all Product-owned
-- commercial/publication fields remain unchanged.
--
-- MS885DW4#XW and MS885DW18#XW have approved manufacturer provenance but no
-- Product rows in the approved input. They are intentionally not fabricated;
-- the membership insert maps only Product rows that actually exist.

CREATE TABLE IF NOT EXISTS product_families (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_key varchar(100) NOT NULL,
  label varchar(200) NOT NULL,
  source varchar(50) NOT NULL DEFAULT 'manual',
  confidence varchar(20) NOT NULL DEFAULT 'medium',
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT product_families_family_key_key UNIQUE (family_key)
);

CREATE TABLE IF NOT EXISTS product_family_configuration_groups (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id integer NOT NULL,
  group_key varchar(100) NOT NULL,
  label varchar(200) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  source varchar(50) NOT NULL DEFAULT 'manual',
  confidence varchar(20) NOT NULL DEFAULT 'medium',
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT uq_product_family_configuration_groups_family_key UNIQUE (family_id, group_key),
  CONSTRAINT uq_product_family_configuration_groups_id_family UNIQUE (id, family_id),
  CONSTRAINT product_family_configuration_groups_family_fkey
    FOREIGN KEY (family_id) REFERENCES product_families(id)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS product_family_memberships (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id integer NOT NULL,
  configuration_group_id integer NOT NULL,
  product_id integer NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  source varchar(50) NOT NULL DEFAULT 'manual',
  confidence varchar(20) NOT NULL DEFAULT 'medium',
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT uq_product_family_memberships_family_product UNIQUE (family_id, product_id),
  CONSTRAINT product_family_memberships_family_fkey
    FOREIGN KEY (family_id) REFERENCES product_families(id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT product_family_memberships_configuration_group_fkey
    FOREIGN KEY (configuration_group_id, family_id)
    REFERENCES product_family_configuration_groups(id, family_id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT product_family_memberships_product_fkey
    FOREIGN KEY (product_id) REFERENCES products(id)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS product_family_catalogue_gaps (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id integer NOT NULL,
  member_key varchar(100) NOT NULL,
  gap_type varchar(50) NOT NULL DEFAULT 'missing_product',
  status varchar(30) NOT NULL DEFAULT 'open',
  source varchar(50) NOT NULL DEFAULT 'manual',
  confidence varchar(20) NOT NULL DEFAULT 'medium',
  note varchar(500),
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT uq_product_family_catalogue_gaps_family_member UNIQUE (family_id, member_key),
  CONSTRAINT product_family_catalogue_gaps_family_fkey
    FOREIGN KEY (family_id) REFERENCES product_families(id)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS idx_product_families_source
  ON product_families (source);
CREATE INDEX IF NOT EXISTS idx_product_family_configuration_groups_order
  ON product_family_configuration_groups (family_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_product_family_memberships_group_order
  ON product_family_memberships (configuration_group_id, sort_order, product_id);
CREATE INDEX IF NOT EXISTS idx_product_family_memberships_family_order
  ON product_family_memberships (family_id, sort_order, product_id);
CREATE INDEX IF NOT EXISTS idx_product_family_catalogue_gaps_status
  ON product_family_catalogue_gaps (family_id, status);

INSERT INTO product_families (family_key, label, source, confidence)
VALUES ('toto:ms885', 'TOTO MS885', 'toto-catalogue', 'high')
ON CONFLICT (family_key) DO UPDATE
SET label = EXCLUDED.label,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    updated_at = now();

WITH approved_groups (group_key, label, sort_order) AS (
  VALUES
    ('ecowasher', 'nắp rửa cơ', 0),
    ('electronic-washlet', 'nắp điện tử', 1),
    ('soft-close', 'nắp đóng êm', 2)
)
INSERT INTO product_family_configuration_groups
  (family_id, group_key, label, sort_order, source, confidence)
SELECT family.id, approved_groups.group_key, approved_groups.label,
       approved_groups.sort_order, 'toto-catalogue', 'high'
FROM product_families family
CROSS JOIN approved_groups
WHERE family.family_key = 'toto:ms885'
ON CONFLICT (family_id, group_key) DO UPDATE
SET label = EXCLUDED.label,
    sort_order = EXCLUDED.sort_order,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    updated_at = now();

-- Keep the approved canonical set in one session-local manifest. This avoids
-- repeating the 21-SKU set across the mapping and integrity checks.
CREATE TEMP TABLE IF NOT EXISTS ms885_approved_members (
  member_key varchar(100) PRIMARY KEY,
  group_key varchar(100) NOT NULL,
  sort_order integer NOT NULL,
  catalogue_gap boolean NOT NULL DEFAULT false
);
TRUNCATE ms885_approved_members;

INSERT INTO ms885_approved_members (member_key, group_key, sort_order, catalogue_gap)
VALUES
  ('MS885DE2#XW', 'ecowasher', 0, false),
  ('MS885DE4#XW', 'ecowasher', 1, false),
  ('MS885DE6#XW', 'ecowasher', 2, false),
  ('MS885DT2#XW', 'soft-close', 3, false),
  ('MS885DT3#XW', 'soft-close', 4, false),
  ('MS885DT8#XW', 'soft-close', 5, false),
  ('MS885DW4#XW', 'electronic-washlet', 6, true),
  ('MS885DW6#XW', 'electronic-washlet', 7, false),
  ('MS885DW7#XW', 'electronic-washlet', 8, false),
  ('MS885DW11#XW', 'electronic-washlet', 9, false),
  ('MS885DW14#XW', 'electronic-washlet', 10, false),
  ('MS885DW16#XW', 'electronic-washlet', 11, false),
  ('MS885DW18#XW', 'electronic-washlet', 12, true),
  ('MS885CDW12#XW', 'electronic-washlet', 13, false),
  ('MS885CDW15#XW', 'electronic-washlet', 14, false),
  ('MS885CDW17#XW', 'electronic-washlet', 15, false),
  ('MS885CDW23#XW', 'electronic-washlet', 16, false),
  ('MS885CDW24#XW', 'electronic-washlet', 17, false),
  ('MS885CDW25#XW', 'electronic-washlet', 18, false),
  ('MS885DW24#XW', 'electronic-washlet', 19, false),
  ('MS885DW25#XW', 'electronic-washlet', 20, false);

-- Persist approved members with no Product row as explicit catalogue gaps.
-- The gap row is not a Product surrogate and contains no commerce data.
INSERT INTO product_family_catalogue_gaps
  (family_id, member_key, gap_type, status, source, confidence, note)
SELECT family.id, approved.member_key, 'missing_product',
       CASE WHEN EXISTS (
         SELECT 1 FROM products product WHERE product.sku = approved.member_key
       ) THEN 'resolved' ELSE 'open' END,
       'toto-catalogue', 'high',
       'Approved canonical member; Product row is not fabricated by M2.3.'
FROM ms885_approved_members approved
JOIN product_families family ON family.family_key = 'toto:ms885'
WHERE approved.catalogue_gap
ON CONFLICT (family_id, member_key) DO UPDATE
SET gap_type = EXCLUDED.gap_type,
    status = EXCLUDED.status,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    note = EXCLUDED.note,
    updated_at = now();

-- Map canonical members only when an exact Product row exists. Missing DW4/DW18
-- remain catalogue gaps rather than fabricated Product rows.
INSERT INTO product_family_memberships
  (family_id, configuration_group_id, product_id, sort_order, source, confidence)
SELECT family.id, configuration_group.id, product.id, approved.sort_order,
       'toto-catalogue', 'high'
FROM ms885_approved_members approved
JOIN products product ON product.sku = approved.member_key
JOIN product_families family ON family.family_key = 'toto:ms885'
JOIN product_family_configuration_groups configuration_group
  ON configuration_group.family_id = family.id
 AND configuration_group.group_key = approved.group_key
ON CONFLICT (family_id, product_id) DO UPDATE
SET configuration_group_id = EXCLUDED.configuration_group_id,
    sort_order = EXCLUDED.sort_order,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    updated_at = now();

-- Fail closed on the exact approved group, membership, and gap contract.
-- A zero-row Product table is valid in an isolated structural replay and
-- produces zero memberships plus two open catalogue gaps.
DO $$
DECLARE
  existing_count integer;
  mapped_count integer;
  mismatch_count integer;
  extra_membership_count integer;
  expected_gap_count integer;
  actual_gap_count integer;
  product_row_count integer;
  missing_required_count integer;
BEGIN
  IF (
    SELECT count(*)
    FROM product_family_configuration_groups configuration_group
    JOIN product_families family ON family.id = configuration_group.family_id
    WHERE family.family_key = 'toto:ms885'
  ) <> 3
  OR (
    SELECT count(*)
    FROM product_family_configuration_groups configuration_group
    JOIN product_families family ON family.id = configuration_group.family_id
    WHERE family.family_key = 'toto:ms885'
      AND configuration_group.group_key IN ('ecowasher', 'electronic-washlet', 'soft-close')
  ) <> 3 THEN
    RAISE EXCEPTION 'MS885 configuration-group contract mismatch';
  END IF;

  SELECT count(*) INTO existing_count
  FROM products product
  JOIN ms885_approved_members approved ON approved.member_key = product.sku;

  SELECT count(*) INTO product_row_count FROM products;

  SELECT count(*) INTO missing_required_count
  FROM ms885_approved_members approved
  LEFT JOIN products product ON product.sku = approved.member_key
  WHERE NOT approved.catalogue_gap
    AND product.id IS NULL;

  SELECT count(*) INTO mapped_count
  FROM product_family_memberships membership
  JOIN products product ON product.id = membership.product_id
  JOIN product_families family ON family.id = membership.family_id
  JOIN ms885_approved_members approved ON approved.member_key = product.sku
  WHERE family.family_key = 'toto:ms885';

  SELECT count(*) INTO mismatch_count
  FROM products product
  JOIN ms885_approved_members approved ON approved.member_key = product.sku
  JOIN product_families family ON family.family_key = 'toto:ms885'
  LEFT JOIN product_family_memberships membership
    ON membership.family_id = family.id
   AND membership.product_id = product.id
  LEFT JOIN product_family_configuration_groups configuration_group
    ON configuration_group.id = membership.configuration_group_id
   AND configuration_group.family_id = family.id
  WHERE membership.id IS NULL
     OR configuration_group.group_key IS DISTINCT FROM approved.group_key;

  SELECT count(*) INTO extra_membership_count
  FROM product_family_memberships membership
  JOIN products product ON product.id = membership.product_id
  JOIN product_families family ON family.id = membership.family_id
  LEFT JOIN ms885_approved_members approved ON approved.member_key = product.sku
  WHERE family.family_key = 'toto:ms885'
    AND approved.member_key IS NULL;

  SELECT count(*) INTO expected_gap_count
  FROM ms885_approved_members
  WHERE catalogue_gap;

  SELECT count(*) INTO actual_gap_count
  FROM product_family_catalogue_gaps gap
  JOIN product_families family ON family.id = gap.family_id
  WHERE family.family_key = 'toto:ms885';

  IF existing_count <> mapped_count
     OR (product_row_count <> 0 AND missing_required_count <> 0)
     OR mismatch_count <> 0
     OR extra_membership_count <> 0 THEN
    RAISE EXCEPTION
      'MS885 normalized membership contract mismatch: existing %, mapped %, missing required %, mismatches %, extras %',
      existing_count, mapped_count, missing_required_count, mismatch_count, extra_membership_count;
  END IF;

  IF product_row_count <> 0 AND EXISTS (
    WITH expected_groups (group_key, expected_without_gaps) AS (
      VALUES
        ('ecowasher', 3),
        ('electronic-washlet', 13),
        ('soft-close', 3)
    ),
    group_counts AS (
      SELECT expected.group_key,
             expected.expected_without_gaps
               + count(product.id) FILTER (WHERE approved.catalogue_gap) AS expected_count,
             count(product.id) AS actual_count
      FROM expected_groups expected
      LEFT JOIN ms885_approved_members approved
        ON approved.group_key = expected.group_key
      LEFT JOIN products product ON product.sku = approved.member_key
      GROUP BY expected.group_key, expected.expected_without_gaps
    )
    SELECT 1 FROM group_counts WHERE expected_count <> actual_count
  ) THEN
    RAISE EXCEPTION 'MS885 configuration-group membership cardinality mismatch';
  END IF;

  IF actual_gap_count <> expected_gap_count
     OR EXISTS (
       SELECT 1
       FROM ms885_approved_members approved
       LEFT JOIN product_families family ON family.family_key = 'toto:ms885'
       LEFT JOIN product_family_catalogue_gaps gap
         ON gap.family_id = family.id
        AND gap.member_key = approved.member_key
       WHERE approved.catalogue_gap AND gap.id IS NULL
     )
     OR EXISTS (
       SELECT 1
       FROM product_family_catalogue_gaps gap
       JOIN product_families family ON family.id = gap.family_id
       LEFT JOIN ms885_approved_members approved
         ON approved.member_key = gap.member_key
        AND approved.catalogue_gap
       WHERE family.family_key = 'toto:ms885'
         AND approved.member_key IS NULL
     ) THEN
    RAISE EXCEPTION 'MS885 catalogue-gap set is not exact';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM ms885_approved_members approved
    JOIN product_families family ON family.family_key = 'toto:ms885'
    JOIN product_family_catalogue_gaps gap
      ON gap.family_id = family.id
     AND gap.member_key = approved.member_key
    LEFT JOIN products product ON product.sku = approved.member_key
    WHERE approved.catalogue_gap
      AND gap.status IS DISTINCT FROM CASE
        WHEN product.id IS NULL THEN 'open' ELSE 'resolved' END
  ) THEN
    RAISE EXCEPTION 'MS885 catalogue-gap status mismatch';
  END IF;
END $$;
