/**
 * Product slug redirects generated by variant pipeline rename scripts.
 * These handle old product URLs → new standardized URLs.
 *
 * Phase 1: Bồn Cầu (212 redirects)
 * Phase 2: Sen Tắm (157 redirects)
 * Phase 3: Lavabo (50 redirects)
 * Phase 4: Bồn Tắm/Tiểu/PK (23 redirects)
 * Phase 6A: Strip Duplicate SKU (2,881 redirects)
 *
 * Import this in next.config.ts
 */

import * as fs from 'fs';
import * as path from 'path';

export type Redirect = {
  source: string;
  destination: string;
  permanent: boolean;
};

function loadRedirectsFromJson(filename: string): Redirect[] {
  const filePath = path.join(process.cwd(), 'scripts/variant-pipeline/output', filename);
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(content) as Redirect[];
  } catch {
    // File not found or invalid — skip silently
    return [];
  }
}

export function getProductRedirects(): Redirect[] {
  return [
    ...loadRedirectsFromJson('phase1-bon-cau-redirects.json'),
    ...loadRedirectsFromJson('phase2-sen-tam-redirects.json'),
    ...loadRedirectsFromJson('phase3-lavabo-redirects.json'),
    ...loadRedirectsFromJson('phase4-mixed-redirects.json'),
    ...loadRedirectsFromJson('phase6a-redirects.json'),
    // Future phases will be added here:
  ];
}
