'use client'

import { useState, useTransition } from 'react'
import { createProductSubType, createProductType, setProductSubTypeActive, setProductTypeActive } from '@/lib/pim-actions'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

type Type = { id: number; subcategory_id: number; name: string; slug: string; is_active: boolean; product_sub_types: { id: number; name: string; slug: string; product_type_id: number; is_active: boolean }[] }
type Subcategory = { id: number; name: string }

export function TypeManager({ types, subcategories }: { types: Type[]; subcategories: Subcategory[] }) {
    const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(''); const [subtypeMessage, setSubtypeMessage] = useState('')
    return <div className="grid gap-6 lg:grid-cols-2">
        <Card><CardHeader><CardTitle className="text-base">Thêm Product Type</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const d = new FormData(event.currentTarget); startTransition(async () => { const result = await createProductType({ subcategory_id: Number(d.get('subcategory_id')), name: d.get('name'), slug: d.get('slug'), is_active: true, sort_order: 0, filter_policy: {} }); setMessage(result.success ? 'Đã tạo Product Type.' : ('message' in result ? result.message : 'Dữ liệu Type không hợp lệ.')) }) }}><div><Label>Subcategory ID</Label><Input name="subcategory_id" type="number" min="1" list="pim-subcategories" required /><datalist id="pim-subcategories">{subcategories.map((subcategory) => <option key={subcategory.id} value={subcategory.id}>{subcategory.name}</option>)}</datalist></div><div><Label>Tên</Label><Input name="name" required /></div><div><Label>Slug</Label><Input name="slug" required /></div><Button disabled={pending}>{pending ? 'Đang lưu…' : 'Tạo Type'}</Button>{message && <p className="text-sm text-muted-foreground">{message}</p>}</form></CardContent></Card>
        <Card><CardHeader><CardTitle className="text-base">Thêm Product Subtype</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const d = new FormData(event.currentTarget); startTransition(async () => { const result = await createProductSubType({ product_type_id: Number(d.get('product_type_id')), name: d.get('subtype_name'), slug: d.get('subtype_slug'), is_active: true, sort_order: 0 }); setSubtypeMessage(result.success ? 'Đã tạo Product Subtype.' : ('message' in result ? result.message : 'Dữ liệu Subtype không hợp lệ.')) }) }}><div><Label>Product Type ID</Label><Input name="product_type_id" type="number" min="1" list="pim-types" required /><datalist id="pim-types">{types.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</datalist></div><div><Label>Tên</Label><Input name="subtype_name" required /></div><div><Label>Slug</Label><Input name="subtype_slug" required /></div><Button disabled={pending}>{pending ? 'Đang lưu…' : 'Tạo Subtype'}</Button>{subtypeMessage && <p className="text-sm text-muted-foreground">{subtypeMessage}</p>}</form></CardContent></Card>
        <Card><CardHeader><CardTitle className="text-base">Product Types hiện có</CardTitle></CardHeader><CardContent><div className="divide-y">{types.map((type) => <div key={type.id} className="py-3 text-sm"><div className="flex items-center justify-between gap-3"><span><strong>#{type.id}</strong> {type.name} <span className="text-muted-foreground">/{type.slug}</span></span><Button variant="ghost" size="sm" disabled={pending} onClick={() => startTransition(async () => { const result = await setProductTypeActive(type.id, !type.is_active); setMessage(result.success ? 'Đã cập nhật Product Type.' : ('message' in result ? result.message : 'Không thể cập nhật Type.')) })}>{type.is_active ? 'active' : 'inactive'}</Button></div>{type.product_sub_types.length > 0 && <div className="mt-1 space-y-1 pl-5 text-muted-foreground">{type.product_sub_types.map((subtype) => <div key={subtype.id} className="flex items-center justify-between gap-3"><span>{subtype.name} ({subtype.slug})</span><Button variant="ghost" size="sm" disabled={pending} onClick={() => startTransition(async () => { const result = await setProductSubTypeActive(subtype.id, !subtype.is_active); setSubtypeMessage(result.success ? 'Đã cập nhật Product Subtype.' : ('message' in result ? result.message : 'Không thể cập nhật Subtype.')) })}>{subtype.is_active ? 'active' : 'inactive'}</Button></div>)}</div>}</div>)}</div></CardContent></Card>
    </div>
}
