import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

// ── Pre-compiled redirect map (source → destination) ────────
// Generated by: scripts/variant-pipeline → src/data/product-redirect-map.json
// Contains 3,323 old-slug → new-slug mappings from Phase 1-6A
import redirectData from "@/data/product-redirect-map.json";

const redirectMap = new Map<string, string>(Object.entries(redirectData));

// ============================================================
// MIDDLEWARE: Maintenance Mode + Product Slug Redirects
// ============================================================

const MAINTENANCE_MODE = process.env.MAINTENANCE_MODE === "true";

const BYPASS_PATHS = [
  "/maintenance",
  "/admin",
  "/api",
  "/_next",
  "/favicon.ico",
  "/images",
  "/banners",
  "/robots.txt",
  "/sitemap.xml",
];

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Skip static/admin/api paths
  if (BYPASS_PATHS.some((path) => pathname.startsWith(path))) {
    return NextResponse.next();
  }

  // ── Maintenance mode ──
  if (MAINTENANCE_MODE) {
    const maintenanceUrl = new URL("/maintenance", request.url);
    return NextResponse.rewrite(maintenanceUrl);
  }

  // ── Product slug 301 redirects ──
  const destination = redirectMap.get(pathname);
  if (destination) {
    const redirectUrl = new URL(destination, request.url);
    return NextResponse.redirect(redirectUrl, 301);
  }

  return NextResponse.next();
}

export const config = {
  matcher: [
    // Match all paths except static files
    "/((?!_next/static|_next/image|favicon.ico).*)",
  ],
};
