CREATE TABLE IF NOT EXISTS catalog_taxons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer,
  name varchar(200) NOT NULL,
  slug varchar(200) NOT NULL,
  canonical_path varchar(500) NOT NULL,
  depth integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS product_taxon_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL,
  taxon_id integer NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  source varchar(40) NOT NULL DEFAULT 'manual',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS external_taxonomy_mappings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source varchar(40) NOT NULL,
  source_category_slug varchar(255) NOT NULL,
  source_category_name varchar(255),
  source_category_path varchar(1000),
  taxon_id integer,
  mapping_type varchar(40) NOT NULL DEFAULT 'taxon',
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS product_attribute_values (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL,
  taxon_id integer,
  attribute_key varchar(120) NOT NULL,
  value_text varchar(255) NOT NULL,
  value_slug varchar(120) NOT NULL,
  source varchar(40) NOT NULL DEFAULT 'manual',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'catalog_taxons_parent_id_fkey'
  ) THEN
    ALTER TABLE catalog_taxons
      ADD CONSTRAINT catalog_taxons_parent_id_fkey
      FOREIGN KEY (parent_id) REFERENCES catalog_taxons(id)
      ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'product_taxon_assignments_product_id_fkey'
  ) THEN
    ALTER TABLE product_taxon_assignments
      ADD CONSTRAINT product_taxon_assignments_product_id_fkey
      FOREIGN KEY (product_id) REFERENCES products(id)
      ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'product_taxon_assignments_taxon_id_fkey'
  ) THEN
    ALTER TABLE product_taxon_assignments
      ADD CONSTRAINT product_taxon_assignments_taxon_id_fkey
      FOREIGN KEY (taxon_id) REFERENCES catalog_taxons(id)
      ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'external_taxonomy_mappings_taxon_id_fkey'
  ) THEN
    ALTER TABLE external_taxonomy_mappings
      ADD CONSTRAINT external_taxonomy_mappings_taxon_id_fkey
      FOREIGN KEY (taxon_id) REFERENCES catalog_taxons(id)
      ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'product_attribute_values_product_id_fkey'
  ) THEN
    ALTER TABLE product_attribute_values
      ADD CONSTRAINT product_attribute_values_product_id_fkey
      FOREIGN KEY (product_id) REFERENCES products(id)
      ON UPDATE NO ACTION ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'product_attribute_values_taxon_id_fkey'
  ) THEN
    ALTER TABLE product_attribute_values
      ADD CONSTRAINT product_attribute_values_taxon_id_fkey
      FOREIGN KEY (taxon_id) REFERENCES catalog_taxons(id)
      ON UPDATE NO ACTION ON DELETE SET NULL;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_catalog_taxons_canonical_path
  ON catalog_taxons (canonical_path);

CREATE UNIQUE INDEX IF NOT EXISTS uq_catalog_taxons_parent_slug
  ON catalog_taxons (parent_id, slug);

CREATE INDEX IF NOT EXISTS idx_catalog_taxons_parent
  ON catalog_taxons (parent_id);

CREATE INDEX IF NOT EXISTS idx_catalog_taxons_slug
  ON catalog_taxons (slug);

CREATE INDEX IF NOT EXISTS idx_catalog_taxons_active
  ON catalog_taxons (is_active);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_taxon_assignments_product_taxon
  ON product_taxon_assignments (product_id, taxon_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_taxon_assignments_primary_product
  ON product_taxon_assignments (product_id)
  WHERE is_primary IS TRUE;

CREATE INDEX IF NOT EXISTS idx_product_taxon_assignments_taxon
  ON product_taxon_assignments (taxon_id);

CREATE INDEX IF NOT EXISTS idx_product_taxon_assignments_product
  ON product_taxon_assignments (product_id);

CREATE INDEX IF NOT EXISTS idx_product_taxon_assignments_source
  ON product_taxon_assignments (source);

CREATE UNIQUE INDEX IF NOT EXISTS uq_external_taxonomy_mappings_source_slug
  ON external_taxonomy_mappings (source, source_category_slug);

CREATE INDEX IF NOT EXISTS idx_external_taxonomy_mappings_source
  ON external_taxonomy_mappings (source);

CREATE INDEX IF NOT EXISTS idx_external_taxonomy_mappings_source_category_slug
  ON external_taxonomy_mappings (source_category_slug);

CREATE INDEX IF NOT EXISTS idx_external_taxonomy_mappings_taxon
  ON external_taxonomy_mappings (taxon_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_attribute_values_product_key_value
  ON product_attribute_values (product_id, attribute_key, value_slug);

CREATE INDEX IF NOT EXISTS idx_product_attribute_values_product
  ON product_attribute_values (product_id);

CREATE INDEX IF NOT EXISTS idx_product_attribute_values_taxon
  ON product_attribute_values (taxon_id);

CREATE INDEX IF NOT EXISTS idx_product_attribute_values_key_value
  ON product_attribute_values (attribute_key, value_slug);

CREATE INDEX IF NOT EXISTS idx_product_attribute_values_source
  ON product_attribute_values (source);

INSERT INTO catalog_taxons (parent_id, name, slug, canonical_path, depth, sort_order, is_active)
VALUES
  (NULL, 'Thiết bị vệ sinh', 'thiet-bi-ve-sinh', 'thiet-bi-ve-sinh', 0, 1, true),
  (NULL, 'Thiết bị bếp', 'thiet-bi-bep', 'thiet-bi-bep', 0, 2, true),
  (NULL, 'Vật liệu nước', 'vat-lieu-nuoc', 'vat-lieu-nuoc', 0, 3, true),
  (NULL, 'Gạch ốp lát', 'gach-op-lat', 'gach-op-lat', 0, 4, true)
ON CONFLICT (canonical_path) DO UPDATE
SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  depth = EXCLUDED.depth,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  updated_at = now();

WITH child_taxons(parent_slug, name, slug, sort_order) AS (
  VALUES
    ('thiet-bi-ve-sinh', 'Bồn cầu', 'bon-cau', 1),
    ('thiet-bi-ve-sinh', 'Nắp bồn cầu', 'nap-bon-cau', 2),
    ('thiet-bi-ve-sinh', 'Lavabo', 'lavabo', 3),
    ('thiet-bi-ve-sinh', 'Vòi chậu', 'voi-chau', 4),
    ('thiet-bi-ve-sinh', 'Sen tắm', 'sen-tam', 5),
    ('thiet-bi-ve-sinh', 'Bồn tắm', 'bon-tam', 6),
    ('thiet-bi-ve-sinh', 'Bồn tiểu', 'bon-tieu', 7),
    ('thiet-bi-ve-sinh', 'Phụ kiện phòng tắm', 'phu-kien-phong-tam', 8),
    ('thiet-bi-ve-sinh', 'Gương phòng tắm', 'guong-phong-tam', 9),
    ('thiet-bi-ve-sinh', 'Ga thoát sàn', 'ga-thoat-san', 10),
    ('thiet-bi-ve-sinh', 'Máy sấy tay', 'may-say-tay', 11),
    ('thiet-bi-bep', 'Chậu rửa chén', 'chau-rua-chen', 1),
    ('thiet-bi-bep', 'Vòi rửa chén', 'voi-rua-chen', 2),
    ('thiet-bi-bep', 'Phụ kiện chậu rửa chén', 'phu-kien-chau-rua-chen', 3),
    ('thiet-bi-bep', 'Bếp điện từ', 'bep-dien-tu', 4),
    ('thiet-bi-bep', 'Bếp gas', 'bep-gas', 5),
    ('thiet-bi-bep', 'Máy hút mùi', 'may-hut-mui', 6),
    ('thiet-bi-bep', 'Máy rửa chén', 'may-rua-chen', 7),
    ('thiet-bi-bep', 'Lò nướng', 'lo-nuong', 8),
    ('thiet-bi-bep', 'Phụ kiện bếp', 'phu-kien-bep', 9),
    ('thiet-bi-bep', 'Thiết bị bếp khác', 'thiet-bi-bep-khac', 10),
    ('vat-lieu-nuoc', 'Máy nước nóng', 'may-nuoc-nong', 1),
    ('vat-lieu-nuoc', 'Lọc nước', 'loc-nuoc', 2),
    ('vat-lieu-nuoc', 'Bồn chứa nước', 'bon-chua-nuoc', 3),
    ('vat-lieu-nuoc', 'Máy bơm nước', 'may-bom-nuoc', 4),
    ('vat-lieu-nuoc', 'Phụ kiện vật liệu nước', 'phu-kien-vat-lieu-nuoc', 5),
    ('gach-op-lat', 'Gạch ốp lát', 'gach-op-lat', 1),
    ('gach-op-lat', 'Gạch ốp tường', 'gach-op-tuong', 2),
    ('gach-op-lat', 'Gạch lát nền', 'gach-lat-nen', 3),
    ('gach-op-lat', 'Gạch trang trí', 'gach-trang-tri', 4),
    ('gach-op-lat', 'Gạch Inax Ecocarat', 'gach-inax-ecocarat', 5)
)
INSERT INTO catalog_taxons (parent_id, name, slug, canonical_path, depth, sort_order, is_active)
SELECT
  parent_taxon.id,
  child_taxons.name,
  child_taxons.slug,
  parent_taxon.canonical_path || '/' || child_taxons.slug,
  1,
  child_taxons.sort_order,
  true
FROM child_taxons
JOIN catalog_taxons AS parent_taxon
  ON parent_taxon.canonical_path = child_taxons.parent_slug
ON CONFLICT (canonical_path) DO UPDATE
SET
  parent_id = EXCLUDED.parent_id,
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  depth = EXCLUDED.depth,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  updated_at = now();
